In [1]:
using CSV, DataFrames, Dates, TSFrames, Statistics, PortfolioAnalytics, LinearAlgebra, TimerOutputs, NearestCorrelationMatrix

# Create a TimerOutput, this will store all our timing information
#const to = TimerOutput();

In [2]:
function load_stocks(data_dir::String, stock_files::Vector{String})
    combined_df = DataFrame()  # Create an empty DataFrame to store the combined data
    
    # Iterate over each stock file
    for file in stock_files
        path = joinpath(data_dir, file)  # Get the full path of the file
        
        if isfile(path)
            # Load the CSV file into a DataFrame
            df = CSV.read(path, DataFrame)
            
            # Select required columns (including the ticker symbol)
            select!(df, [:Date, :Ticker, :Close, :Sector])
            
            # Append the DataFrame to the combined DataFrame
            append!(combined_df, df)
        else
            println("File not found: $file")  # Print an error if file is missing
        end
    end
    
    return combined_df
end

load_stocks (generic function with 1 method)

In [3]:
# Specify the data directory and list of stock files to load
data_dir = "C:/Users/Z2005081/Downloads/COPY FROM SCHOOL PC/DATA_MINNER/FULL_2020_2025_11_SECTION"
stock_files = [
    "Consumer_Discretionary.csv", "Consumer_Staples.csv", "Energy.csv",
    "Financials.csv", "Health_Care.csv", "Industrials.csv",         # Note: It must be UFT-8 CSV
    "Information_Technology.csv", "Materials.csv", "Real_Estate.csv", "Communication_Services.csv", "Utilities.csv"
]

# Call the function to load the stocks
combined_df = load_stocks(data_dir, stock_files)

# Display the combined DataFrame
println("\nStock Data:\n")
show(combined_df)


Stock Data:

716100×4 DataFrame
    Row │ Date                       Ticker   Close    Sector                 
        │ String31                   String7  Float64  String31               
────────┼─────────────────────────────────────────────────────────────────────
      1 │ 2020-01-02 00:00:00-05:00  AMZN     94.9005  Consumer Discretionary
      2 │ 2020-01-03 00:00:00-05:00  AMZN     93.7485  Consumer Discretionary
      3 │ 2020-01-06 00:00:00-05:00  AMZN     95.144   Consumer Discretionary
      4 │ 2020-01-07 00:00:00-05:00  AMZN     95.343   Consumer Discretionary
      5 │ 2020-01-08 00:00:00-05:00  AMZN     94.5985  Consumer Discretionary
      6 │ 2020-01-09 00:00:00-05:00  AMZN     95.0525  Consumer Discretionary
      7 │ 2020-01-10 00:00:00-05:00  AMZN     94.158   Consumer Discretionary
      8 │ 2020-01-13 00:00:00-05:00  AMZN     94.565   Consumer Discretionary
      9 │ 2020-01-14 00:00:00-05:00  AMZN     93.472   Consumer Discretionary
     10 │ 2020-01-15 00:00:0

In [4]:
df = DataFrame(combined_df)

# Group by sector and count the number of stocks in each sector
sector_counts = combine(groupby(df, :Sector), DataFrames.nrow => :Count)

# Display the count of stocks in each sector
println("\nNumber of Stocks in Each Sector:\n")
show(sector_counts, allrows=true, allcols=true)



Number of Stocks in Each Sector:

11×2 DataFrame
 Row │ Sector                  Count 
     │ String31                Int64 
─────┼───────────────────────────────
   1 │ Consumer Discretionary  65100
   2 │ Consumer Staples        65100
   3 │ Energy                  65100
   4 │ Financials              65100
   5 │ Health Care             65100
   6 │ Industrials             65100
   7 │ Information Technology  65100
   8 │ Materials               65100
   9 │ Real Estate             65100
  10 │ Communication Services  65100
  11 │ Utilities               65100

In [5]:
df = DataFrame(combined_df)

# Group by sector and count the number of unique tickers in each sector
sector_ticker_counts = combine(groupby(df, :Sector), :Ticker => (tickers -> length(unique(tickers))) => :Ticker_Count)

# Display the count of unique tickers in each sector
println("\nNumber of Unique Tickers in Each Sector:\n")
show(sector_ticker_counts, allrows=true, allcols=true)



Number of Unique Tickers in Each Sector:

11×2 DataFrame
 Row │ Sector                  Ticker_Count 
     │ String31                Int64        
─────┼──────────────────────────────────────
   1 │ Consumer Discretionary            50
   2 │ Consumer Staples                  50
   3 │ Energy                            50
   4 │ Financials                        50
   5 │ Health Care                       50
   6 │ Industrials                       50
   7 │ Information Technology            50
   8 │ Materials                         50
   9 │ Real Estate                       50
  10 │ Communication Services            50
  11 │ Utilities                         50

In [6]:
# Count the number of unique stocks (replace "Ticker" with the actual column name)
num_stocks = length(unique(combined_df.Ticker))
println("\nNumber of unique stocks: ", num_stocks)


550ber of unique stocks: 


In [7]:
println("Unique tickers in daily_df: ", length(unique(combined_df.Ticker)))

Unique tickers in daily_df: 550


In [8]:
# Extract and print all unique tickers (replace "Ticker" with your actual column name)
unique_tickers = sort(unique(combined_df.Ticker))  # Sorting for easier reading
println("\nUnique Stock Tickers:")
for ticker in unique_tickers
    println(ticker)
end

# Print the total number of unique tickers
println("\nTotal number of unique stocks: ", length(unique_tickers))


Unique Stock Tickers:
A
AA
AAL
AAP
AAPL
ABBV
ABT
ACN
ADBE
ADC
ADI
ADM
ADP
AEE
AEP
AES
AFL
AIG
AJG
AKAM
ALB
ALE
ALGN
ALL
ALLE
ALLY
AMAT
AMD
AMGN
AMP
AMT
AMX
AMZN
ANSS
AOS
APA
APD
APH
AR
ARE
ARTNA
ASH
ATI
ATO
ATUS
AVA
AVB
AVGO
AVT
AVY
AWK
AWR
AXP
AZO
BA
BAC
BALL
BBY
BCPC
BDX
BEN
BG
BHP
BIDU
BIIB
BILI
BIO
BK
BKH
BKNG
BKR
BLK
BMY
BP
BR
BRX
BSX
BURL
BXP
C
CABO
CACC
CAG
CAH
CASY
CAT
CB
CBT
CC
CCI
CCOI
CDNS
CE
CF
CFG
CHD
CHTR
CHWY
CHX
CI
CL
CLF
CLX
CMC
CMCSA
CME
CMG
CMI
CMS
CNC
CNP
CNQ
COF
COP
COST
COTY
CPB
CPT
CRM
CSCO
CSX
CTAS
CTRA
CTSH
CTVA
CUBE
CVE
CVS
CVX
CWT
CZR
D
DAL
DAR
DD
DE
DEA
DEI
DEO
DFS
DG
DGX
DHI
DHR
DINO
DIS
DLR
DNP
DOC
DOV
DOW
DOYU
DRI
DTE
DUK
DVA
DVN
DXC
E
EA
EBAY
EC
ECL
ED
EFX
EGP
EIX
EL
ELV
EMN
EMR
ENB
EOG
EQIX
EQNR
EQR
EQT
ES
ESS
ETN
ETSY
EVRG
EW
EXC
EXP
EXPD
EXR
F
FANG
FAST
FCX
FDP
FDS
FDX
FE
FIS
FITB
FIZZ
FLO
FLS
FMC
FND
FOX
FR
FRT
FTI
FTNT
FUL
FWONA
GD
GE
GILD
GIS
GLW
GM
GMRE
GNE
GOOG
GPC
GPN
GRMN
GS
GWW
HAIN
HAL
HAS
HBAN
HCA
HD
HE
HES
HII
HIW
HLT
HOLX
HON
HP
HPQ
HR
HR

In [60]:
# Extract unique tickers from the combined DataFrame
tickers = unique(combined_df.Ticker)

# Filter the combined DataFrame by the extracted tickers
filtered_df = filter(:Ticker => t -> t in tickers, combined_df)

# Select only the required columns
filtered_df = filtered_df[:, ["Date", "Ticker", "Close"]]

# Correctly parse the DateTime with the specified format
filtered_df[!, "Date"] = DateTime.(filtered_df.Date, "yyyy-mm-dd HH:MM:SS-HH:MM")

# Define the date range for filtering
start_date = DateTime("2024-01-02")
end_date = DateTime("2025-03-08")


# Filter the DataFrame for the specified date range
daily_df = filter(row -> start_date <= row.Date <= end_date, filtered_df)

# Sort the DataFrame by Date and Ticker
sort!(daily_df, [:Date, :Ticker])


162800×3 DataFrame
    Row │ Date                 Ticker   Close    
        │ DateTime             String7  Float64  
────────┼────────────────────────────────────────
      1 │ 2024-01-02T05:00:00  A        137.794
      2 │ 2024-01-02T05:00:00  AA        32.816
      3 │ 2024-01-02T05:00:00  AAL       13.44
      4 │ 2024-01-02T05:00:00  AAP       60.5056
      5 │ 2024-01-02T05:00:00  AAPL     184.532
      6 │ 2024-01-02T05:00:00  ABBV     152.743
      7 │ 2024-01-02T05:00:00  ABT      107.138
      8 │ 2024-01-02T05:00:00  ACN      341.431
      9 │ 2024-01-02T05:00:00  ADBE     580.07
     10 │ 2024-01-02T05:00:00  ADC       60.2293
     11 │ 2024-01-02T05:00:00  ADI      189.526
   ⋮    │          ⋮              ⋮        ⋮
 162791 │ 2025-03-07T05:00:00  XEL       68.0
 162792 │ 2025-03-07T05:00:00  XOM      109.02
 162793 │ 2025-03-07T05:00:00  XRAY      16.32
 162794 │ 2025-03-07T05:00:00  XYL      130.62
 162795 │ 2025-03-07T05:00:00  YORW      34.48
 162796 │ 2025-03-07T05:00:00  YUM      162.53
 162797 │ 2025-03-07T05:00:00  ZBRA     292.69
 162798 │ 2025-03-07T05:00:00  ZG        73.85
 162799 │ 2025-03-07T05:00:00  ZM        75.98
 162800 │ 2025-03-07T05:00:00  ZTS      170.37
                              162779 rows omitted

In [61]:
# Pivot the DataFrame to get the desired format, handling duplicates by taking the mean
pivoted_df = unstack(daily_df, :Date, :Ticker, :Close, combine = mean)

# Sort by Date (Index)
sort!(pivoted_df, :Date)

# Convert the DataFrame to a TSFrame
tsframe = TSFrame(pivoted_df, :Date)


296×550 TSFrame with DateTime Index
 Index                A         AA        AAL       AAP       AAPL      ABBV   ⋯
 DateTime             Float64?  Float64?  Float64?  Float64?  Float64?  Float6 ⋯
────────────────────────────────────────────────────────────────────────────────
 2024-01-02T05:00:00   137.794   32.816      13.44   60.5056   184.532   152.7 ⋯
 2024-01-03T05:00:00   130.256   31.023      12.95   59.5778   183.15    153.3
 2024-01-04T05:00:00   130.097   30.6684     13.09   59.0797   180.824   154.3
 2024-01-05T05:00:00   129.66    31.6535     13.6    60.0856   180.099   154.9
 2024-01-08T05:00:00   132.461   31.2595     14.58   60.4665   184.453   154.2 ⋯
 2024-01-09T05:00:00   129.779   31.4663     14.38   59.9587   184.035   155.1
 2024-01-10T05:00:00   130.187   31.1806     14.35   59.5582   185.079   157.5
 2024-01-11T05:00:00   128.786   30.4221     14.59   61.2254   184.482   156.5
 2024-01-12T05:00:00   129.64    29.5847     13.21   60.1172   184.81    156.6 ⋯
 202

In [62]:
all_tickers = unique(daily_df.Ticker)
pivoted_df = unstack(daily_df, :Date, :Ticker, :Close, combine = mean)
for ticker in setdiff(all_tickers, names(pivoted_df)[2:end])
    pivoted_df[!, ticker] = fill(NaN, nrow(pivoted_df))
end

In [63]:
# Calculate the log returns for each stock
asset_returns = asset_return(tsframe, method = "log")

# Extract returns as vectors for correlation analysis
returns_vectors = Dict(ticker => collect(skipmissing(asset_returns[:, ticker])) for ticker in names(asset_returns)[1:end])

# Convert the returns vectors to a DataFrame for better visualization
returns_df = DataFrame(returns_vectors)


295×550 DataFrame
 Row │ A             AA            AAL          AAP           AAPL          AB ⋯
     │ Float64       Float64       Float64      Float64       Float64       Fl ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ -0.0562558    -0.0561878    -0.0371395   -0.0154538    -0.00751575    0 ⋯
   2 │ -0.00122057   -0.0114979     0.0107528   -0.00839572   -0.0127816     0
   3 │ -0.00336453    0.0316182     0.0382212    0.0168841    -0.00402098    0
   4 │  0.0213694    -0.0125276     0.0695809    0.00631949    0.0238872    -0
   5 │ -0.0204507     0.00659655   -0.0138124   -0.00843479   -0.00226591    0 ⋯
   6 │  0.00313257   -0.00912101   -0.00208839  -0.00670101    0.00565535    0
   7 │ -0.0108142    -0.0246295     0.0165864    0.0276081    -0.00322781   -0
   8 │  0.00660986   -0.0279117    -0.0993623   -0.0182661     0.00177655    0
   9 │ -7.66262e-5   -0.0746461    -0.00151519   0.00163002   -0.0123936    -0 ⋯
  10 │ -0.0186358    -0.0250695    -0.0199087   -0.00588045   -0.00518682    0
  11 │  0.0180995    -0.0159469     0.0665666    0.0183431     0.0320514     0
  ⋮  │      ⋮             ⋮             ⋮            ⋮             ⋮           ⋱
 286 │ -0.000665039   0.0178627     0.0052391   -0.0146089     0.00629253    0
 287 │ -0.00816457   -0.0187353    -0.0118267    0.0692576    -0.000242898   0 ⋯
 288 │  0.00215901   -0.0205768     0.00329926  -0.196369     -0.0274124    -0
 289 │ -0.0565243    -0.00715356   -0.0437633   -0.0198239    -0.0128126     0
 290 │  0.00658823   -0.0053989    -0.0124655   -0.00162463    0.0189512     0
 291 │ -0.0125075    -0.0594787    -0.0340217   -0.0412173    -0.0158796     0 ⋯
 292 │ -0.0262255    -0.00256492   -0.0382118   -0.0237187    -0.00886159   -0
 293 │  0.0276494     0.0387267     0.0539489   -0.00667356   -0.000805594   0
 294 │  0.000316138   0.0138018    -0.0614678   -0.0211834    -0.00174073   -0
 295 │  0.00118455    0.000304502  -0.0167432    0.0504454     0.0157676     0 ⋯
                                                545 columns and 274 rows omitted

In [64]:
# Convert the DataFrame to a matrix
returns_matrix = Matrix(returns_df)


295×550 Matrix{Float64}:
 -0.0562558    -0.0561878    -0.0371395   …  -0.0290514    -0.0186913
 -0.00122057   -0.0114979     0.0107528      -0.0040277     0.00573702
 -0.00336453    0.0316182     0.0382212       0.000896423   0.00416562
  0.0213694    -0.0125276     0.0695809       0.0211312     0.00664964
 -0.0204507     0.00659655   -0.0138124      -0.00117047   -0.00107122
  0.00313257   -0.00912101   -0.00208839  …  -0.00190486    0.0143399
 -0.0108142    -0.0246295     0.0165864       0.00468247   -0.0104178
  0.00660986   -0.0279117    -0.0993623       0.0282114     0.0112727
 -7.66262e-5   -0.0746461    -0.00151519     -0.0194905    -0.0303648
 -0.0186358    -0.0250695    -0.0199087      -0.0167826    -0.0108888
  0.0180995    -0.0159469     0.0665666   …  -0.00931473    0.000167991
  0.00580839    0.0225476    -0.011645        0.0252287    -0.0111909
  0.0100847     0.0094581    -0.00293255      0.00793477    0.0148588
  ⋮                                       ⋱                

In [67]:
A = cor(returns_matrix)


550×550 Matrix{Float64}:
 1.0         0.180324    0.179886    …   0.309042    0.228446    0.283332
 0.180324    1.0         0.238562        0.234882    0.119067    0.137479
 0.179886    0.238562    1.0             0.191537    0.149666    0.113521
 0.171505    0.169227    0.215886        0.188025    0.00192242  0.139253
 0.109031    0.139368    0.146015        0.232247    0.17866     0.127991
 0.174613   -0.0151612   0.0291155   …   0.0699976  -0.0361176   0.141966
 0.226759   -0.0430993   0.0168183       0.0571697   0.117557    0.293217
 0.258958    0.127923    0.149801        0.116319    0.288045    0.173855
 0.138474    0.0399881   0.147147        0.234428    0.210228    0.086072
 0.178138    0.0714902   0.0277416       0.164553    0.0471774   0.317152
 0.377385    0.31267     0.253275    …   0.251523    0.196444    0.177118
 0.0706985   0.13969     0.0587523       0.0187841   0.0255106   0.032967
 0.180588    0.0412681   0.142261        0.151448    0.181324    0.0823327
 ⋮          

In [68]:
eigvals(A)

550-element Vector{Float64}:
  -9.790324997736502e-15
  -8.887280656269296e-15
  -4.711371334814133e-15
  -3.865521854499892e-15
  -3.6031778059943086e-15
  -3.407822472397583e-15
  -3.167020226034407e-15
  -2.796474980776787e-15
  -2.669356124742055e-15
  -2.565714648039858e-15
  -2.2271619451824195e-15
  -2.2030497917076423e-15
  -2.103563099610509e-15
   ⋮
   5.332937181563127
   5.762241144572178
   6.093873520391833
   6.461197532053829
   6.990073749550197
   8.636126735811605
  10.5992666758315
  14.03573532157519
  16.29948868153619
  23.426399745610723
  43.41436704988023
 110.1124918636684

In [69]:
using LinearAlgebra
using Random
using TimerOutputs

In [70]:
# Function to project onto the PSD matrix
function Project_onto_PSD(A_symm::Matrix{Float64})::Matrix{Float64}
    λ, V = eigen(Symmetric(A_symm))  # Eigenvalue decomposition
    λ[λ .< 0] .= 0.0  # Set all negative eigenvalues exactly to zero
    return V * Diagonal(λ) * V'  # Reconstruct PSD matrix
end

Project_onto_PSD (generic function with 1 method)

In [71]:
# Function to project onto the unit diagonal (in-place modification)
function project_onto_UD!(A_symm::Matrix{Float64})::Matrix{Float64}
    for i in 1:size(A_symm,1)
        A_symm[i,i] = 1.0
    end
    return A_symm
end

project_onto_UD! (generic function with 1 method)

In [75]:
# Function for POCS with Dykstra's Correction
function nearest_corr_dykstra(A_symm::Matrix{Float64}, tol::Float64=1e-8, max_iter::Int=1000000)
    Y_k = copy(A_symm)
    ΔS_k = zeros(size(A_symm))

    for k in 1:max_iter
        R_k = Y_k - ΔS_k
        X_k = Project_onto_PSD(R_k)
        ΔS_k = X_k - R_k
        Y_k = project_onto_UD!(copy(X_k))  # Ensure no in-place modification to X_k

        # Convergence check (relative error)
        if norm(Y_k - X_k, Inf) / norm(Y_k, Inf) <= tol
            println("Converged after $k iterations")
            return Y_k, k
        end
    end
    println("Reached maximum iterations ($max_iter) without convergence")
    return Y_k, max_iter
end

nearest_corr_dykstra (generic function with 3 methods)

In [76]:
# ===== Example Usage ===== #
# Pass in the symmetric matrix (not necessarily a valid correlation matrix)


A_symm = (A + A') / 2  # Make it symmetric

# Run the nearest correlation matrix function
to = TimerOutput()  # Initialize timing
println("=== POCS with Dykstra ===")

@timeit to "POCS with Dykstra" begin
    result, iterations = nearest_corr_dykstra(A_symm)
end

show(to)

# Verify the result is PSD
min_eigenval = minimum(eigen(Symmetric(result)).values)
println("")
println("Minimum Eigenvalue after projection: ", min_eigenval)
result

=== POCS with Dykstra ===
Converged after 1 iterations
──────────────────────────────────────────────────────────────────────────────
                                     Time                    Allocations      
                            ───────────────────────   ────────────────────────
     Tot / % measured:           197ms /  97.8%           26.3MiB /  99.9%    

Section             ncalls     time    %tot     avg     alloc    %tot      avg
──────────────────────────────────────────────────────────────────────────────
POCS with Dykstra        1    193ms  100.0%   193ms   26.3MiB  100.0%  26.3MiB
──────────────────────────────────────────────────────────────────────────────
Minimum Eigenvalue after projection: -1.499094601010266e-14


550×550 Matrix{Float64}:
 1.0         0.180324    0.179886    …   0.309042    0.228446    0.283332
 0.180324    1.0         0.238562        0.234882    0.119067    0.137479
 0.179886    0.238562    1.0             0.191537    0.149666    0.113521
 0.171505    0.169227    0.215886        0.188025    0.00192242  0.139253
 0.109031    0.139368    0.146015        0.232247    0.17866     0.127991
 0.174613   -0.0151612   0.0291155   …   0.0699976  -0.0361176   0.141966
 0.226759   -0.0430993   0.0168183       0.0571697   0.117557    0.293217
 0.258958    0.127923    0.149801        0.116319    0.288045    0.173855
 0.138474    0.0399881   0.147147        0.234428    0.210228    0.086072
 0.178138    0.0714902   0.0277416       0.164553    0.0471774   0.317152
 0.377385    0.31267     0.253275    …   0.251523    0.196444    0.177118
 0.0706985   0.13969     0.0587523       0.0187841   0.0255106   0.032967
 0.180588    0.0412681   0.142261        0.151448    0.181324    0.0823327
 ⋮          

In [77]:
eigvals(result)

550-element Vector{ComplexF64}:
  -3.974064830718866e-15 + 0.0im
  -3.326034694031045e-15 + 0.0im
 -2.8202128197104143e-15 - 1.117833780699321e-16im
 -2.8202128197104143e-15 + 1.117833780699321e-16im
 -2.6183202381707636e-15 + 0.0im
 -2.4665477637545403e-15 - 1.303550826005758e-16im
 -2.4665477637545403e-15 + 1.303550826005758e-16im
  -2.452370325024852e-15 + 0.0im
  -2.264588873868899e-15 - 1.783599720252432e-16im
  -2.264588873868899e-15 + 1.783599720252432e-16im
 -2.1208980729590884e-15 - 3.6692652240909735e-16im
 -2.1208980729590884e-15 + 3.6692652240909735e-16im
 -2.1012025747906937e-15 - 1.5269203745016495e-16im
                         ⋮
       5.332937181563107 + 0.0im
      5.7622411445722195 + 0.0im
       6.093873520391853 + 0.0im
       6.461197532053897 + 0.0im
       6.990073749550237 + 0.0im
        8.63612673581165 + 0.0im
      10.599266675831528 + 0.0im
      14.035735321575276 + 0.0im
       16.29948868153617 + 0.0im
      23.426399745610738 + 0.0im
       43.4143670

In [23]:

# Enforce small eigenvalues to be a small positive value
function enforce_small_eigenvalues_positive!(matrix::Matrix{Float64}, threshold::Float64=1e-8, small_positive::Float64=1e-6)
    λ, V = eigen(Symmetric(matrix))
    λ[λ .< threshold] .= small_positive
    matrix .= V * Diagonal(λ) * V'
    return Symmetric(matrix)
end

enforce_small_eigenvalues_positive! (generic function with 3 methods)

In [24]:
# Function to project onto the unit diagonal (in-place modification)
function project_onto_UD!(A::Matrix{Float64})::Matrix{Float64}
    for i in 1:size(A, 1)
        A[i, i] = 1.0
    end
    return A
end

project_onto_UD! (generic function with 1 method)

In [25]:
# Function to project onto the PSD cone
function Project_onto_PSD(matrix::Matrix{Float64})::Matrix{Float64}
    λ, V = eigen(Symmetric(matrix))
    λ[λ .< 0] .= 0
    return V * Diagonal(λ) * V'
end

Project_onto_PSD (generic function with 1 method)

In [26]:
# Function for POCS with Dykstra's Correction
function nearest_corr_dykstra(A::Matrix{Float64}, tol::Float64=1e-8, max_iter::Int=10000)
    Y_k = copy(A)
    ΔS_k = zeros(size(A))

    for k in 1:max_iter
        R_k = Y_k - ΔS_k
        X_k = @timeit to "proj_PSD" Project_onto_PSD(R_k)
        ΔS_k = X_k - R_k
        Y_k = @timeit to "proj_UD" project_onto_UD!(copy(X_k))  # Ensure no in-place modification to X_k

        # Convergence check: Ensure changes are small
        if norm(Y_k - X_k, Inf) <= tol * max(norm(Y_k, Inf), eps(Float64))
            println("Converged after $k iterations")
            return Y_k, k
        end
    end
    println("Reached maximum iterations ($max_iter) without convergence")
    return Y_k, max_iter
end

nearest_corr_dykstra (generic function with 3 methods)

In [27]:
# Define Matrix
@time Returns_Matrix  # Define a symmetric matrix

to = TimerOutput()  # Initialize timing
println("=== POCS with Dykstra ===")
@timeit to "POCS with Dykstra" begin
    result, iterations = nearest_corr_dykstra(Returns_Matrix)
end

show(to) 

# Verify the result is PSD
min_eigenval = minimum(eigen(Symmetric(result)).values);


println(" ");
 println("Minimum Eigenvalue after projection: ", min_eigenval);

# Apply the function to the result matrix
result = enforce_small_eigenvalues_positive!(result);
#println("Eigenvalues after enforcing small positive values: ", eigvals(result));

  0.000002 seconds
=== POCS with Dykstra ===
Converged after 1 iterations
──────────────────────────────────────────────────────────────────────────────
                                     Time                    Allocations      
                            ───────────────────────   ────────────────────────
     Tot / % measured:           530ms /  99.1%           38.8MiB /  99.9%    

Section             ncalls     time    %tot     avg     alloc    %tot      avg
──────────────────────────────────────────────────────────────────────────────
POCS with Dykstra        1    525ms  100.0%   525ms   38.8MiB  100.0%  38.8MiB
  proj_PSD               1    134ms   25.4%   134ms   11.7MiB   30.3%  11.7MiB
  proj_UD                1   1.02ms    0.2%  1.02ms   2.31MiB    6.0%  2.31MiB
────────────────────────────────────────────────────────────────────────────── 
Minimum Eigenvalue after projection: 0.017080992878056752


In [28]:
result

550×550 Symmetric{Float64, Matrix{Float64}}:
 1.0       0.341684   0.291481   …  0.398537   0.222342    0.588853
 0.341684  1.0        0.453693      0.315123   0.0304738   0.291048
 0.291481  0.453693   1.0           0.296137   0.0164447   0.227405
 0.313961  0.313672   0.280062      0.255597   0.0435602   0.312147
 0.48978   0.306628   0.286348      0.405074   0.283077    0.53075
 0.348814  0.175168   0.136149   …  0.154286  -0.0349751   0.395757
 0.555384  0.185457   0.176073      0.278671   0.140008    0.563973
 0.563609  0.389523   0.343428      0.372454   0.2045      0.55957
 0.482745  0.227748   0.211223      0.417845   0.353948    0.478927
 0.351186  0.303158   0.307349      0.365073   0.0140673   0.427558
 0.554107  0.443891   0.36101    …  0.465851   0.226888    0.481578
 0.347397  0.435498   0.315121      0.166931  -0.0538514   0.300916
 0.511121  0.357705   0.362572      0.345502   0.0797917   0.548638
 ⋮                               ⋱                         
 0.514498  0.

In [29]:
eigvals(result)

550-element Vector{Float64}:
   0.017080992878057265
   0.01871712060762831
   0.01954749645360226
   0.019978980549153515
   0.02067697190946732
   0.02109590639371449
   0.021421645017632187
   0.02269889510960254
   0.022971009107125653
   0.023621000389374716
   0.02407213901508395
   0.02450544899786704
   0.02535173213479776
   ⋮
   3.9087487060765866
   4.125967269853987
   4.510806169979932
   4.898846527791914
   5.58734725499009
   6.033147897610605
   7.712303265236992
   9.471092905317402
  12.330409298835317
  24.930980682859936
  32.72933160863599
 211.12389412400785

In [30]:
rank(result)

550

In [31]:
# Checking Frobenius norm
frobenius_norm = norm(Returns_Matrix-result)  
println(frobenius_norm)

1.1532233022175007e-12
