# Packages

In [1]:
using CSV, DataFrames, Dates, TSFrames, Statistics, PortfolioAnalytics, LinearAlgebra, TimerOutputs, NearestCorrelationMatrix, NaNStatistics, LinearAlgebra.LAPACK

# Create a TimerOutput, this will store all our timing information
const to = TimerOutput();

Load Data Function

In [2]:
function load_stocks(data_dir::String, stock_files::Vector{String})
    combined_df = DataFrame()  # Create an empty DataFrame to store the combined data
    
    # Iterate over each stock file
    for file in stock_files
        path = joinpath(data_dir, file)  # Get the full path of the file
        
        if isfile(path)
            # Load the CSV file into a DataFrame
            df = CSV.read(path, DataFrame)
            
            # Select required columns (including the ticker symbol)
            select!(df, [:Date, :Ticker, :Close, :Sector])
            
            # Append the DataFrame to the combined DataFrame
            append!(combined_df, df)
        else
            println("File not found: $file")  # Print an error if file is missing
        end
    end
    
    return combined_df
end

load_stocks (generic function with 1 method)

In [3]:
# Specify the data directory and list of stock files to load
data_dir = "C:/Users/Z2005081/Downloads/COPY FROM SCHOOL PC/DATA_MINNER/FULL_2020_2025_11_SECTION"
stock_files = [
    "Consumer_Discretionary.csv", "Consumer_Staples.csv", "Energy.csv",
    "Financials.csv", "Health_Care.csv", "Industrials.csv",         # Note: It must be UFT-8 CSV
    "Information_Technology.csv", "Materials.csv", "Real_Estate.csv", "Communication_Services.csv", "Utilities.csv"
]

# Call the function to load the stocks
combined_df = load_stocks(data_dir, stock_files)

# Display the combined DataFrame
println("\nStock Data:\n")
show(combined_df)


Stock Data:

716100×4 DataFrame
    Row │ Date                       Ticker   Close    Sector                 
        │ String31                   String7  Float64  String31               
────────┼─────────────────────────────────────────────────────────────────────
      1 │ 2020-01-02 00:00:00-05:00  AMZN     94.9005  Consumer Discretionary
      2 │ 2020-01-03 00:00:00-05:00  AMZN     93.7485  Consumer Discretionary
      3 │ 2020-01-06 00:00:00-05:00  AMZN     95.144   Consumer Discretionary
      4 │ 2020-01-07 00:00:00-05:00  AMZN     95.343   Consumer Discretionary
      5 │ 2020-01-08 00:00:00-05:00  AMZN     94.5985  Consumer Discretionary
      6 │ 2020-01-09 00:00:00-05:00  AMZN     95.0525  Consumer Discretionary
      7 │ 2020-01-10 00:00:00-05:00  AMZN     94.158   Consumer Discretionary
      8 │ 2020-01-13 00:00:00-05:00  AMZN     94.565   Consumer Discretionary
      9 │ 2020-01-14 00:00:00-05:00  AMZN     93.472   Consumer Discretionary
     10 │ 2020-01-15 00:00:0

In [4]:
df = DataFrame(combined_df)

# Group by sector and count the number of stocks in each sector
sector_counts = combine(groupby(df, :Sector), DataFrames.nrow => :Count)

# Display the count of stocks in each sector
println("\nNumber of Stocks in Each Sector:\n")
show(sector_counts, allrows=true, allcols=true)



Number of Stocks in Each Sector:

11×2 DataFrame
 Row │ Sector                  Count 
     │ String31                Int64 
─────┼───────────────────────────────
   1 │ Consumer Discretionary  65100
   2 │ Consumer Staples        65100
   3 │ Energy                  65100
   4 │ Financials              65100
   5 │ Health Care             65100
   6 │ Industrials             65100
   7 │ Information Technology  65100
   8 │ Materials               65100
   9 │ Real Estate             65100
  10 │ Communication Services  65100
  11 │ Utilities               65100

In [5]:
df = DataFrame(combined_df)

# Group by sector and count the number of unique tickers in each sector
sector_ticker_counts = combine(groupby(df, :Sector), :Ticker => (tickers -> length(unique(tickers))) => :Ticker_Count)

# Display the count of unique tickers in each sector
println("\nNumber of Unique Tickers in Each Sector:\n")
show(sector_ticker_counts, allrows=true, allcols=true)



Number of Unique Tickers in Each Sector:

11×2 DataFrame
 Row │ Sector                  Ticker_Count 
     │ String31                Int64        
─────┼──────────────────────────────────────
   1 │ Consumer Discretionary            50
   2 │ Consumer Staples                  50
   3 │ Energy                            50
   4 │ Financials                        50
   5 │ Health Care                       50
   6 │ Industrials                       50
   7 │ Information Technology            50
   8 │ Materials                         50
   9 │ Real Estate                       50
  10 │ Communication Services            50
  11 │ Utilities                         50

In [6]:
# Count the number of unique stocks (replace "Ticker" with the actual column name)
num_stocks = length(unique(combined_df.Ticker))
println("\nNumber of unique stocks: ", num_stocks)


Number of unique stocks: 550


In [7]:
# Extract and print all unique tickers (replace "Ticker" with your actual column name)
unique_tickers = sort(unique(combined_df.Ticker))  # Sorting for easier reading
println("\nUnique Stock Tickers:")
for ticker in unique_tickers
    println(ticker)
end

# Print the total number of unique tickers
println("\nTotal number of unique stocks: ", length(unique_tickers))


Unique Stock Tickers:
A
AA
AAL
AAP
AAPL
ABBV
ABT
ACN
ADBE
ADC
ADI
ADM
ADP
AEE
AEP
AES
AFL
AIG
AJG
AKAM
ALB
ALE
ALGN
ALL
ALLE
ALLY
AMAT
AMD
AMGN
AMP
AMT
AMX
AMZN
ANSS
AOS
APA
APD
APH
AR
ARE
ARTNA
ASH
ATI
ATO
ATUS
AVA
AVB
AVGO
AVT
AVY
AWK
AWR
AXP
AZO
BA
BAC
BALL
BBY
BCPC
BDX
BEN
BG
BHP
BIDU
BIIB
BILI
BIO
BK
BKH
BKNG
BKR
BLK
BMY
BP
BR
BRX
BSX
BURL
BXP
C
CABO
CACC
CAG
CAH
CASY
CAT
CB
CBT
CC
CCI
CCOI
CDNS
CE
CF
CFG
CHD
CHTR
CHWY
CHX
CI
CL
CLF
CLX
CMC
CMCSA
CME
CMG
CMI
CMS
CNC
CNP
CNQ
COF
COP
COST
COTY
CPB
CPT
CRM
CSCO
CSX
CTAS
CTRA
CTSH
CTVA
CUBE
CVE
CVS
CVX
CWT
CZR
D
DAL
DAR
DD
DE
DEA
DEI
DEO
DFS
DG
DGX
DHI
DHR
DINO
DIS
DLR
DNP
DOC
DOV
DOW
DOYU
DRI
DTE
DUK
DVA
DVN
DXC
E
EA
EBAY
EC
ECL
ED
EFX
EGP
EIX
EL
ELV
EMN
EMR
ENB
EOG
EQIX
EQNR
EQR
EQT
ES
ESS
ETN
ETSY
EVRG
EW
EXC
EXP
EXPD
EXR
F
FANG
FAST
FCX
FDP
FDS
FDX
FE
FIS
FITB
FIZZ
FLO
FLS
FMC
FND
FOX
FR
FRT
FTI
FTNT
FUL
FWONA
GD
GE
GILD
GIS
GLW
GM
GMRE
GNE
GOOG
GPC
GPN
GRMN
GS
GWW
HAIN
HAL
HAS
HBAN
HCA
HD
HE
HES
HII
HIW
HLT
HOLX
HON
HP
HPQ
HR
HR

In [8]:
# Extract unique tickers from the combined DataFrame
tickers = unique(combined_df.Ticker)

# Filter the combined DataFrame by the extracted tickers
filtered_df = filter(:Ticker => t -> t in tickers, combined_df)

# Select only the required columns
filtered_df = filtered_df[:, ["Date", "Ticker", "Close"]]

# Correctly parse the DateTime with the specified format
filtered_df[!, "Date"] = DateTime.(filtered_df.Date, "yyyy-mm-dd HH:MM:SS-HH:MM")

# Define the date range for filtering
start_date = DateTime("2020-01-02")
end_date = DateTime("2025-03-08")


# Filter the DataFrame for the specified date range
daily_df = filter(row -> start_date <= row.Date <= end_date, filtered_df)

# Sort the DataFrame by Date and Ticker
sort!(daily_df, [:Date, :Ticker])


716100×3 DataFrame
    Row │ Date                 Ticker   Close    
        │ DateTime             String7  Float64  
────────┼────────────────────────────────────────
      1 │ 2020-01-02T05:00:00  A         83.0613
      2 │ 2020-01-02T05:00:00  AA        20.6555
      3 │ 2020-01-02T05:00:00  AAL       28.9829
      4 │ 2020-01-02T05:00:00  AAP      143.805
      5 │ 2020-01-02T05:00:00  AAPL      72.7161
      6 │ 2020-01-02T05:00:00  ABBV      71.5898
      7 │ 2020-01-02T05:00:00  ABT       79.2739
      8 │ 2020-01-02T05:00:00  ACN      195.264
      9 │ 2020-01-02T05:00:00  ADBE     334.43
     10 │ 2020-01-02T05:00:00  ADC       54.5435
     11 │ 2020-01-02T05:00:00  ADI      109.436
   ⋮    │          ⋮              ⋮        ⋮
 716091 │ 2025-03-07T05:00:00  XEL       68.0
 716092 │ 2025-03-07T05:00:00  XOM      109.02
 716093 │ 2025-03-07T05:00:00  XRAY      16.32
 716094 │ 2025-03-07T05:00:00  XYL      130.62
 716095 │ 2025-03-07T05:00:00  YORW      34.48
 716096 │ 2025-03-07T05:00:00  YUM      162.53
 716097 │ 2025-03-07T05:00:00  ZBRA     292.69
 716098 │ 2025-03-07T05:00:00  ZG        73.85
 716099 │ 2025-03-07T05:00:00  ZM        75.98
 716100 │ 2025-03-07T05:00:00  ZTS      170.37
                              716079 rows omitted

In [9]:
# Pivot the DataFrame to get the desired format, handling duplicates by taking the mean
pivoted_df = unstack(daily_df, :Date, :Ticker, :Close, combine = mean)

# Sort by Date (Index)
sort!(pivoted_df, :Date)

# Convert the DataFrame to a TSFrame
tsframe = TSFrame(pivoted_df, :Date)


1302×550 TSFrame with DateTime Index
 Index                A         AA        AAL       AAP       AAPL      ABBV   ⋯
 DateTime             Float64?  Float64?  Float64?  Float64?  Float64?  Float6 ⋯
────────────────────────────────────────────────────────────────────────────────
 2020-01-02T05:00:00   83.0613   20.6555   28.9829   143.805   72.7161   71.58 ⋯
 2020-01-03T05:00:00   81.7277   20.7326   27.5482   143.814   72.0091   70.91
 2020-01-06T05:00:00   81.9693   20.2505   27.2194   141.451   72.5829   71.46
 2020-01-07T05:00:00   82.2206   20.559    27.1198   139.773   72.2416   71.06
 2020-01-08T05:00:00   83.0323   19.7297   27.7375   138.167   73.4036   71.56 ⋯
 2020-01-09T05:00:00   84.337    19.1029   27.8471   137.905   74.9628   72.11
 2020-01-10T05:00:00   84.6462   18.7558   27.2194   134.423   75.1323   71.19
 2020-01-13T05:00:00   84.5206   18.9101   27.2892   131.04    76.7374   70.76
 2020-01-14T05:00:00   85.0328   19.6429   27.4286   134.324   75.7012   71.46 ⋯
 20

# Log Returns

In [10]:

all_tickers = unique(daily_df.Ticker)
pivoted_df = unstack(daily_df, :Date, :Ticker, :Close, combine = mean)
for ticker in setdiff(all_tickers, names(pivoted_df)[2:end])
    pivoted_df[!, ticker] = fill(NaN, nrow(pivoted_df))
end
     

In [11]:
# Calculate the log returns for each stock
asset_returns = asset_return(tsframe, method = "log")

# Extract returns as vectors for correlation analysis
returns_vectors = Dict(ticker => collect(skipmissing(asset_returns[:, ticker])) for ticker in names(asset_returns)[1:end])

# Convert the returns vectors to a DataFrame for better visualization
returns_df = DataFrame(returns_vectors)


1301×550 DataFrame
  Row │ A             AA            AAL          AAP           AAPL          A ⋯
      │ Float64       Float64       Float64      Float64       Float64       F ⋯
──────┼─────────────────────────────────────────────────────────────────────────
    1 │ -0.0161859     0.00372787   -0.0507687    6.26014e-5   -0.00976959   - ⋯
    2 │  0.0029518    -0.0235305    -0.0120067   -0.0165713     0.00793653
    3 │  0.00306068    0.0151229    -0.00366705  -0.0119329    -0.00471395   -
    4 │  0.00982453   -0.0411738     0.0225219   -0.0115549     0.0159581
    5 │  0.0155901    -0.0322847     0.00394341  -0.00189513    0.0210185      ⋯
    6 │  0.00366022   -0.0183398    -0.0227982   -0.0255748     0.00225799   -
    7 │ -0.0014855     0.00819257    0.00255895  -0.025488      0.0211394    -
    8 │  0.00604186    0.0380235     0.0050984    0.0247497    -0.0135954
    9 │  0.00713438   -0.0093709     0.00181449   0.00875938   -0.0042945      ⋯
   10 │  0.00943384   -0.126618      0.0232944    0.0114513     0.0124486
   11 │  0.00735077   -0.00507464    0.00600385  -0.00587488    0.0110101    -
  ⋮   │      ⋮             ⋮             ⋮            ⋮             ⋮          ⋱
 1292 │ -0.000665039   0.0178627     0.0052391   -0.0146089     0.00629253
 1293 │ -0.00816457   -0.0187353    -0.0118267    0.0692576    -0.000242898    ⋯
 1294 │  0.00215901   -0.0205768     0.00329926  -0.196369     -0.0274124    -
 1295 │ -0.0565243    -0.00715356   -0.0437633   -0.0198239    -0.0128126
 1296 │  0.00658823   -0.0053989    -0.0124655   -0.00162463    0.0189512
 1297 │ -0.0125075    -0.0594787    -0.0340217   -0.0412173    -0.0158796      ⋯
 1298 │ -0.0262255    -0.00256492   -0.0382118   -0.0237187    -0.00886159   -
 1299 │  0.0276494     0.0387267     0.0539489   -0.00667356   -0.000805594
 1300 │  0.000316138   0.0138018    -0.0614678   -0.0211834    -0.00174073   -
 1301 │  0.00118455    0.000304502  -0.0167432    0.0504454     0.0157676      ⋯
                                               545 columns and 1280 rows omitted

In [12]:
# Convert the DataFrame to a matrix
returns_matrix = Matrix(returns_df)

1301×550 Matrix{Float64}:
 -0.0161859     0.00372787   -0.0507687   …  -0.0211773     0.000149
  0.0029518    -0.0235305    -0.0120067       0.0441933    -0.00770718
  0.00306068    0.0151229    -0.00366705      0.02222       0.00337452
  0.00982453   -0.0411738     0.0225219       0.00899974   -0.00217363
  0.0155901    -0.0322847     0.00394341      0.000964382   0.0131923
  0.00366022   -0.0183398    -0.0227982   …   0.0064511     0.00376903
 -0.0014855     0.00819257    0.00255895      0.0127789     0.00690948
  0.00604186    0.0380235     0.0050984      -0.0118215     0.00555206
  0.00713438   -0.0093709     0.00181449      0.0503771     0.00920914
  0.00943384   -0.126618      0.0232944      -0.0108463     0.00648478
  0.00735077   -0.00507464    0.00600385  …  -0.00725266    0.00658564
 -0.00567519   -0.0327523    -0.0431721       0.0153658     0.0125495
  0.005786     -0.0314474     0.004402       -0.0156305    -0.00303439
  ⋮                                       ⋱            

# Unbiased or Random Test

In [13]:
using Random
# Function to randomly delete data (set to NaN)
function delete_random_data!(matrix::Matrix{Float64}, fraction::Float64)
    Random.seed!(10)  # For reproducibility
    for i in 1:size(matrix, 1)
        for j in 1:size(matrix, 2)
            if rand() < fraction
                matrix[i, j] = NaN
            end
        end
    end
    return matrix
end

# Apply the deletion (e.g., % of values set to NaN)
delete_random_data!(returns_matrix, 0.10)
println("Number of NaNs after deletion: ", sum(isnan.(returns_matrix)))            

Number of NaNs after deletion: 71341


# Systematic or NonRandom Test

In [13]:
using Random

# Function to systematically delete data (set to NaN) - High Market Volatility scenario
function delete_systematic_data!(matrix::Matrix{Float64}, fraction::Float64)
    Random.seed!(10)  # For reproducibility, matching your original
    n_rows, n_cols = size(matrix)
    total_elements = n_rows * n_cols
    target_nans = round(Int, fraction * total_elements)  # Number of elements to delete
    
    # Get indices of largest absolute values
    abs_matrix = abs.(matrix)
    sorted_indices = sortperm(vec(abs_matrix), rev=true)[1:target_nans]
    
    # Convert to row, col indices and delete systematically
    deleted = 0
    for i in 1:n_rows
        for j in 1:n_cols
            idx = (i - 1) * n_cols + j
            if deleted < target_nans && idx in sorted_indices
                matrix[i, j] = NaN
                deleted += 1
            end
            if deleted >= target_nans
                break
            end
        end
    end
    return matrix
end

# Apply the deletion (e.g., % of values set to NaN)
delete_systematic_data!(returns_matrix, 0.10)
println("Number of NaNs after deletion: ", sum(isnan.(returns_matrix)))

Number of NaNs after deletion: 71555


In [14]:
returns_matrix

1301×550 Matrix{Float64}:
  -0.0161859      0.00372787    -0.0507687   …   -0.0211773      0.000149
   0.0029518     -0.0235305     -0.0120067        0.0441933     -0.00770718
   0.00306068     0.0151229     -0.00366705       0.02222        0.00337452
   0.00982453   NaN            NaN                0.00899974   NaN
   0.0155901    NaN              0.00394341       0.000964382    0.0131923
 NaN            NaN             -0.0227982   …  NaN              0.00376903
  -0.0014855    NaN              0.00255895       0.0127789      0.00690948
   0.00604186     0.0380235      0.0050984       -0.0118215      0.00555206
   0.00713438    -0.0093709      0.00181449       0.0503771      0.00920914
   0.00943384   NaN              0.0232944       -0.0108463    NaN
 NaN             -0.00507464     0.00600385  …   -0.00725266     0.00658564
  -0.00567519    -0.0327523     -0.0431721        0.0153658      0.0125495
   0.005786      -0.0314474      0.004402        -0.0156305     -0.00303439
   ⋮    

In [15]:
A = nancor(returns_matrix)

550×550 Matrix{Float64}:
 1.0       0.34492    0.32201    …  0.404028   0.204819     0.593038
 0.34492   1.0        0.473082      0.323283   0.0228245    0.321212
 0.32201   0.473082   1.0           0.300558   0.0340184    0.262689
 0.310438  0.309972   0.272927      0.264437   0.0315718    0.320683
 0.501395  0.293163   0.27607       0.411081   0.300205     0.551506
 0.357309  0.186766   0.154534   …  0.160977  -0.0442058    0.400803
 0.565849  0.189216   0.169759      0.296528   0.116273     0.574368
 0.562899  0.400731   0.343719      0.362712   0.189758     0.580954
 0.471129  0.251868   0.216241      0.417812   0.360154     0.477865
 0.359503  0.307352   0.308413      0.368489   0.0192455    0.459563
 0.532993  0.427813   0.389233   …  0.425752   0.249782     0.409082
 0.353797  0.428891   0.312964      0.167875  -0.0668485    0.318026
 0.538381  0.343857   0.413257      0.324738   0.0582425    0.527872
 ⋮                               ⋱                          
 0.531364  0.5189

In [16]:
eigvals(A)

550-element Vector{Float64}:
  -0.5832688256851079
  -0.3750338606304373
  -0.3297424937556781
  -0.29952384266358517
  -0.2890144250767294
  -0.26141336411989397
  -0.23514219429231717
  -0.21070757706942464
  -0.19806047014047595
  -0.19492005214453828
  -0.17835937656529421
  -0.16817756888387822
  -0.16574197728822504
   ⋮
   4.097417428946954
   4.731151344831297
   4.921201682156586
   5.086907128458434
   5.739977937700132
   6.206346178614631
   7.894065803329069
   9.715323508426144
  12.465188438227255
  25.400767835817863
  33.46175052273608
 210.11470511650333

In [17]:
# Symmetrized result already computed
x = eigvals(Symmetric(A))

# Count positive and negative eigenvalues
count_positive = sum(x .> 1e-8)  # Positive, above tolerance
count_negative = sum(x .< -1e-8) # Negative, below tolerance
count_zero = sum(abs.(x) .<= 1e-8)  # Effectively zero

# Print results
println("Number of positive eigenvalues: ", count_positive)
println("Number of negative eigenvalues: ", count_negative)
println("Number of zero eigenvalues: ", count_zero)
println("Is positive semi-definite: ", all(x .>= -1e-8))

Number of positive eigenvalues: 454
Number of negative eigenvalues: 96
Number of zero eigenvalues: 0
Is positive semi-definite: false


# Lapack Method 

In [18]:
using MKL  # Add Intel MKL for optimized LAPACK
# Function to project onto the PSD matrix using LAPACK with MKL
function Project_onto_PSD_LAPACK!(A_symm::Matrix{Float64}, result2::Matrix{Float64}, timer::TimerOutput=to)
    @timeit timer "Project_onto_PSD_LAPACK" begin
        n = size(A_symm, 1)
        F = copy(A_symm)  # Make a copy since LAPACK modifies in-place
        # Compute eigenvalues and eigenvectors using LAPACK with MKL
        λ, _ = LAPACK.syev!('V', 'U', F)  # Extract only eigenvalues
        # Set negative eigenvalues to zero
        λ .= max.(λ, 0.0)
        # Efficient reconstruction: X = V * Diag(λ) * V'
        mul!(result2, F * Diagonal(λ), F')
    end
    return nothing
end

Project_onto_PSD_LAPACK! (generic function with 2 methods)

In [19]:
# Function to project onto the unit diagonal (in-place)
function project_onto_UD!(A_symm::Matrix{Float64}, timer::TimerOutput=to)
    @timeit timer "project_onto_UD!" begin
        for i in 1:size(A_symm, 1)
            A_symm[i, i] = 1.0
        end
    end
    return A_symm
end

project_onto_UD! (generic function with 2 methods)

In [20]:
# Function for POCS with Dykstra's Correction
function nearest_corr_dykstra(A_symm::Matrix{Float64}, tol::Float64=1e-8, max_iter::Int=300, timer::TimerOutput=to)
    Y_k = copy(A_symm)
    ΔS_k = zeros(size(A_symm))
    R_k = similar(A_symm)
    X_k = similar(A_symm)
    diff_matrix = similar(A_symm)

    @timeit timer "nearest_corr_dykstra" begin
        for k in 1:max_iter
            R_k .= Y_k .- ΔS_k
            Project_onto_PSD_LAPACK!(R_k, X_k, timer)
            ΔS_k .= X_k .- R_k
            copyto!(Y_k, X_k)
            project_onto_UD!(Y_k, timer)
            diff_matrix .= Y_k .- X_k
            if norm(diff_matrix, Inf) / max(norm(Y_k, Inf), eps(Float64)) <= tol
                println("Converged after $k iterations")
                return Y_k, k
            end
        end
        println("Reached maximum iterations ($max_iter) without convergence")
        return Y_k, max_iter
    end
end

nearest_corr_dykstra (generic function with 4 methods)

In [32]:
# Example Usage
  # Define A explicitly
A_symm = A  # Ensure symmetry

println("=== POCS with Dykstra Using LAPACK (MKL) ===")
reset_timer!(to)
result2, iterations = nearest_corr_dykstra(A_symm)
show(to)
min_eigenval = minimum(eigen(Symmetric(result2)).values)
diagonal_check = all(abs.(diag(result2) .- 1.0) .< 1e-10)
println("\nMinimum Eigenvalue after projection: ", min_eigenval)
println("Diagonal all ones: ", diagonal_check)
println("|| A - X ||_F: ", norm(A_symm - result2))

=== POCS with Dykstra Using LAPACK (MKL) ===
Converged after 29 iterations
─────────────────────────────────────────────────────────────────────────────────
                                        Time                    Allocations      
                               ───────────────────────   ────────────────────────
       Tot / % measured:            1.51s /  99.8%            351MiB /  96.7%    

Section                ncalls     time    %tot     avg     alloc    %tot      avg
─────────────────────────────────────────────────────────────────────────────────
nearest_corr_dykstra        1    1.51s  100.0%   1.51s    340MiB  100.0%   340MiB
  Project_onto_PSD         29    1.32s   87.2%  45.5ms    340MiB  100.0%  11.7MiB
  project_onto_UD!         29    243μs    0.0%  8.39μs     0.00B    0.0%    0.00B
─────────────────────────────────────────────────────────────────────────────────
Minimum Eigenvalue after projection: -4.954629556096642e-9
Diagonal all ones: true
|| A - X ||_F: 1.3330

In [22]:
using LinearAlgebra

# Symmetrized result already computed
x = eigvals(Symmetric(result2))

# Count positive and negative eigenvalues
count_positive = sum(x .> 1e-8)  # Positive, above tolerance
count_negative = sum(x .< -1e-8) # Negative, below tolerance
count_zero = sum(abs.(x) .<= 1e-8)  # Effectively zero

# Print results
println("Number of positive eigenvalues: ", count_positive)
println("Number of negative eigenvalues: ", count_negative)
println("Number of zero eigenvalues: ", count_zero)
println("Is positive semi-definite: ", all(x .>= -1e-8))

Number of positive eigenvalues: 432
Number of negative eigenvalues: 0
Number of zero eigenvalues: 118
Is positive semi-definite: true


In [23]:
rank(result2)

453

# Plot

### Unbiased Test

In [ ]:
using Plots, LinearAlgebra, PyPlot

# Set PyPlot backend
Plots.pyplot()  # Switch to PyPlot backend
Plots.default(size=(800, 600))  # Set plot size

# Verify data
println("Checking data...")
@assert isdefined(Main, :A) "Matrix A is not defined!"
@assert isdefined(Main, :result2) "Matrix result2 is not defined!"

# Compute and sort eigenvalues
eigvals_A = sort(eigvals(Symmetric(A)), rev=true)
eigvals_result2 = sort(eigvals(Symmetric(result2)), rev=true)

println("Eigenvalues of A: min = ", minimum(eigvals_A), ", max = ", maximum(eigvals_A))
println("Eigenvalues of result: min = ", minimum(eigvals_result2), ", max = ", maximum(eigvals_result2))

# Shift negatives for log scale
eigvals_A_plot = max.(eigvals_A, 1e-10)
eigvals_result_plot = max.(eigvals_result2, 1e-10)

# Create the plot
p = Plots.plot(
    eigvals_A_plot,
    label="Before Projection",
    color=:blue,
    linewidth=2,
    marker=:circle,
    markersize=3,
    yscale=:log10,
    title="10% Eigenvalue Spectrum for Unbiased_test: Before vs After PSD Projection",
    xlabel="Eigenvalue Index",
    ylabel="Eigenvalue Magnitude (log scale)",
    grid=true,
    legend=:topright,
    ylims=(1e-10, 1e3),
    yticks=10.0 .^ (-10:2:2)  # [1e-10, 1e-8, 1e-6, 1e-4, 1e-2, 1e0, 1e2]
)

Plots.plot!(
    eigvals_result_plot,
    label="After Projection",
    color=:red,
    linewidth=2,
    linestyle=:dash,
    marker=:square,
    markersize=3
)

Plots.hline!([1e-10], label="Zero Threshold (approx)", color=:black, linestyle=:dot, linewidth=1)

# Save and implicitly display with PyPlot
println("Saving to 'eigenvalue_spectrum_pyplot.png'...")
Plots.savefig(p, "eigenvalue_spectrum_pyplot_10%_Unbiased_test.png")
println("Saved. Check 'eigenvalue_spectrum_pyplot_10%_Unbiased_test.png'.")

### Systematic Test

In [ ]:
using Plots, LinearAlgebra, PyPlot

# Set PyPlot backend
Plots.pyplot()  # Switch to PyPlot backend
Plots.default(size=(800, 600))  # Set plot size

# Verify data
println("Checking data...")
@assert isdefined(Main, :A) "Matrix A is not defined!"
@assert isdefined(Main, :result2) "Matrix result2 is not defined!"

# Compute and sort eigenvalues
eigvals_A = sort(eigvals(Symmetric(A)), rev=true)
eigvals_result2 = sort(eigvals(Symmetric(result2)), rev=true)

println("Eigenvalues of A: min = ", minimum(eigvals_A), ", max = ", maximum(eigvals_A))
println("Eigenvalues of result: min = ", minimum(eigvals_result2), ", max = ", maximum(eigvals_result2))

# Shift negatives for log scale
eigvals_A_plot = max.(eigvals_A, 1e-10)
eigvals_result_plot = max.(eigvals_result2, 1e-10)

# Create the plot
p = Plots.plot(
    eigvals_A_plot,
    label="Before Projection",
    color=:blue,
    linewidth=2,
    marker=:circle,
    markersize=3,
    yscale=:log10,
    title="10% Eigenvalue Spectrum for Systematic_test: Before vs After PSD Projection",
    xlabel="Eigenvalue Index",
    ylabel="Eigenvalue Magnitude (log scale)",
    grid=true,
    legend=:topright,
    ylims=(1e-10, 1e3),
    yticks=10.0 .^ (-10:2:2)  
)

Plots.plot!(
    eigvals_result_plot,
    label="After Projection",
    color=:red,
    linewidth=2,
    linestyle=:dash,
    marker=:square,
    markersize=3
)

Plots.hline!([1e-10], label="Zero Threshold (approx)", color=:black, linestyle=:dot, linewidth=1)

# Save and implicitly display with PyPlot
println("Saving to 'eigenvalue_spectrum_pyplot.png'...")
Plots.savefig(p, "eigenvalue_spectrum_pyplot_10%__systematic_test.png")
println("Saved. Check 'eigenvalue_spectrum_pyplot_10%_systematic_test.png'.")

# Eigen Method

In [24]:
# Function to project onto the PSD matrix with timing
function Project_onto_PSD(A_symm::Matrix{Float64}, timer::TimerOutput=to)::Matrix{Float64}
    local result3
    @timeit timer "Project_onto_PSD" begin
        λ, V = eigen(Symmetric(A_symm))  # Eigenvalue decomposition
        λ[λ .< 0] .= 0.0  # Set all negative eigenvalues exactly to zero
        result3 = V * Diagonal(λ) * V'  # Reconstruct PSD matrix
    end
    return result3
end

Project_onto_PSD (generic function with 2 methods)

In [25]:
# Function to project onto the unit diagonal (in-place) with timing
function project_onto_UD!(A_symm::Matrix{Float64}, timer::TimerOutput=to)::Matrix{Float64}
    @timeit timer "project_onto_UD!" begin
        for i in 1:size(A_symm, 1)
            A_symm[i, i] = 1.0
        end
    end
    return A_symm
end

project_onto_UD! (generic function with 2 methods)

In [26]:
# Function for POCS with Dykstra's Correction with timing
function nearest_corr_dykstra(A_symm::Matrix{Float64}, tol::Float64=1e-8, max_iter::Int=200, timer::TimerOutput=to)
    # Preallocate matrices for memory efficiency
    Y_k = copy(A_symm)
    ΔS_k = zeros(size(A_symm))
    R_k = similar(A_symm)
    X_k = similar(A_symm)
    diff_matrix = similar(A_symm)

    @timeit timer "nearest_corr_dykstra" begin
        for k in 1:max_iter
            # Compute R_k = Y_k - ΔS_k in place
            R_k .= Y_k .- ΔS_k

            # Project R_k onto PSD cone with timing
            X_k .= Project_onto_PSD(R_k, timer)

            # Update ΔS_k = X_k - R_k in place
            ΔS_k .= X_k .- R_k

            # Project X_k onto unit diagonal in place with timing
            Y_k .= X_k
            project_onto_UD!(Y_k, timer)

            # Convergence check
            diff_matrix .= Y_k .- X_k
            if norm(diff_matrix, Inf) / norm(Y_k, Inf) <= tol
                println("Converged after $k iterations")
                return Y_k, k
            end
        end
        println("Reached maximum iterations ($max_iter) without convergence")
        return Y_k, max_iter
    end
end

nearest_corr_dykstra (generic function with 4 methods)

In [27]:
# Example usage with timing
A_symm = A  # Matrix

println("=== POCS with Dykstra Using Eigen ===")
reset_timer!(to)  # Clear previous timings
result3, iterations = nearest_corr_dykstra(A_symm)
show(to)

# Verify the result is PSD
min_eigenval = minimum(eigen(Symmetric(result3)).values)
println("\nMinimum Eigenvalue after projection: ", min_eigenval)
println("|| A - X ||_F:: ", norm(A_symm - result3))

=== POCS with Dykstra Using Eigen ===
Converged after 29 iterations
─────────────────────────────────────────────────────────────────────────────────
                                        Time                    Allocations      
                               ───────────────────────   ────────────────────────
       Tot / % measured:            2.92s /  71.1%            377MiB /  90.1%    

Section                ncalls     time    %tot     avg     alloc    %tot      avg
─────────────────────────────────────────────────────────────────────────────────
nearest_corr_dykstra        1    2.08s  100.0%   2.08s    340MiB  100.0%   340MiB
  Project_onto_PSD         29    1.84s   88.7%  63.6ms    340MiB  100.0%  11.7MiB
  project_onto_UD!         29    223μs    0.0%  7.70μs     0.00B    0.0%    0.00B
─────────────────────────────────────────────────────────────────────────────────
Minimum Eigenvalue after projection: -4.954629556096642e-9
|| A - X ||_F:: 1.333041291534535


In [28]:
eigvals(result3)

550-element Vector{Float64}:
  -4.954629411540074e-9
  -4.724756958744916e-10
  -3.979708198274856e-10
  -3.7460915816127406e-10
  -3.450891564359191e-10
  -2.994286365414639e-10
  -2.7600835610988073e-10
  -2.328565404060836e-10
  -1.783348738807504e-10
  -1.7131353557657506e-10
  -1.600307686382018e-10
  -1.3057797833277733e-10
  -9.027740733281986e-11
   ⋮
   4.076574730764756
   4.7087766223590695
   4.901225185367131
   5.064028166742509
   5.719413652543906
   6.188066594189247
   7.874967340381684
   9.691917452485406
  12.439416539098923
  25.38161225058139
  33.43674923587626
 210.09153150533422

In [29]:
using LinearAlgebra

# Symmetrized result already computed
x = eigvals(Symmetric(result3))

# Count positive and negative eigenvalues
count_positive = sum(x .> 1e-8)  # Positive, above tolerance
count_negative = sum(x .< -1e-8) # Negative, below tolerance
count_zero = sum(abs.(x) .<= 1e-8)  # Effectively zero

# Print results
println("Number of positive eigenvalues: ", count_positive)
println("Number of negative eigenvalues: ", count_negative)
println("Number of zero eigenvalues: ", count_zero)
println("Is positive semi-definite: ", all(x .>= -1e-8))

Number of positive eigenvalues: 432
Number of negative eigenvalues: 0
Number of zero eigenvalues: 118
Is positive semi-definite: true


In [30]:
result3

550×550 Matrix{Float64}:
 1.0       0.345046   0.32654    …  0.404653   0.20465      0.595391
 0.345046  1.0        0.473267      0.324137   0.0239388    0.322087
 0.32654   0.473267   1.0           0.305221   0.0356668    0.262806
 0.3109    0.312774   0.271207      0.264231   0.031936     0.324595
 0.502384  0.292606   0.278683      0.414113   0.29878      0.550155
 0.356752  0.188693   0.148823   …  0.160239  -0.0447787    0.401963
 0.567843  0.189998   0.180641      0.298983   0.117137     0.574794
 0.567283  0.402942   0.344257      0.365315   0.189907     0.585831
 0.473677  0.252698   0.214609      0.421741   0.360945     0.479552
 0.358936  0.306753   0.305805      0.367337   0.0186232    0.459546
 0.533739  0.425594   0.390093   …  0.42647    0.247445     0.408485
 0.356724  0.42978    0.314845      0.167498  -0.0657078    0.321252
 0.53313   0.343514   0.406512      0.32327    0.0575061    0.528442
 ⋮                               ⋱                          
 0.532904  0.5181

# Online Tools

In [33]:
using NearestCorrelationMatrix
online1 = nearest_cor(A, AlternatingProjections())

550×550 Matrix{Float64}:
 1.0       0.345046   0.32654    …  0.404653   0.20465      0.595391
 0.345046  1.0        0.473267      0.324137   0.0239388    0.322087
 0.32654   0.473267   1.0           0.305221   0.0356668    0.262806
 0.3109    0.312774   0.271207      0.264231   0.031936     0.324595
 0.502384  0.292606   0.278683      0.414113   0.29878      0.550155
 0.356752  0.188693   0.148823   …  0.160239  -0.0447787    0.401963
 0.567843  0.189998   0.180641      0.298983   0.117137     0.574794
 0.567283  0.402942   0.344257      0.365315   0.189907     0.585831
 0.473677  0.252698   0.214609      0.421741   0.360945     0.479552
 0.358936  0.306753   0.305805      0.367337   0.0186232    0.459546
 0.533739  0.425594   0.390093   …  0.42647    0.247445     0.408485
 0.356724  0.42978    0.314845      0.167498  -0.0657078    0.321252
 0.53313   0.343514   0.406512      0.32327    0.0575061    0.528442
 ⋮                               ⋱                          
 0.532904  0.5181

In [34]:
eigvals(online1)

550-element Vector{Float64}:
   1.490115429141762e-8
   1.4901154438254503e-8
   1.4901154912018882e-8
   1.4901155168914437e-8
   1.4901155201848061e-8
   1.4901155293703791e-8
   1.4901155429294809e-8
   1.490115589862534e-8
   1.4901156025708015e-8
   1.490115617234856e-8
   1.4901156295907415e-8
   1.4901156434922595e-8
   1.4901156633790754e-8
   ⋮
   4.076574717663307
   4.7087766070363966
   4.901225170344071
   5.064028148717967
   5.719413634076921
   6.18806657700665
   7.874967316265456
   9.691917417406698
  12.439416488996788
  25.38161217139766
  33.436749104342866
 210.09153074411932

In [35]:
online2 = nearest_cor(A, Newton())

550×550 Symmetric{Float64, Matrix{Float64}}:
 1.0       0.345046   0.32654    …  0.404653   0.20465      0.595391
 0.345046  1.0        0.473267      0.324137   0.0239388    0.322087
 0.32654   0.473267   1.0           0.305221   0.0356668    0.262806
 0.3109    0.312774   0.271207      0.264231   0.031936     0.324595
 0.502384  0.292606   0.278683      0.414113   0.29878      0.550155
 0.356752  0.188693   0.148823   …  0.160239  -0.0447787    0.401963
 0.567843  0.189998   0.180641      0.298983   0.117137     0.574794
 0.567283  0.402942   0.344257      0.365315   0.189907     0.585831
 0.473677  0.252698   0.214609      0.421741   0.360945     0.479552
 0.358936  0.306753   0.305805      0.367337   0.0186232    0.459546
 0.533739  0.425594   0.390093   …  0.42647    0.247445     0.408485
 0.356724  0.42978    0.314845      0.167498  -0.0657078    0.321252
 0.53313   0.343514   0.406512      0.32327    0.0575061    0.528442
 ⋮                               ⋱                        

In [36]:
eigvals(online2)

550-element Vector{Float64}:
   2.020351444723263e-12
   2.4781822075307613e-12
   2.6550630819025213e-12
   3.3061886209347046e-12
   3.877700932229131e-12
   4.135459626224817e-12
   4.409529981487643e-12
   4.565115612876682e-12
   4.808804848189755e-12
   5.262369725004095e-12
   6.328196433180939e-12
   6.644398579611052e-12
   7.199559768306757e-12
   ⋮
   4.0765747295132435
   4.708776620222534
   4.901225183976073
   5.0640281648901775
   5.71941365091228
   6.188066591884908
   7.874967337667829
   9.691917448742256
  12.439416533423397
  25.381612240901067
  33.43674922032424
 210.09153140399394

In [37]:
online3 = nearest_cor(A, DirectProjection())

550×550 Matrix{Float64}:
 1.0       0.341775   0.316844   …  0.401168   0.203403    0.589538
 0.341775  1.0        0.460935      0.321868   0.0237267   0.31948
 0.316844  0.460935   1.0           0.29626    0.0346867   0.255781
 0.306915  0.3092     0.263412      0.261661   0.0317604   0.320732
 0.496325  0.289979   0.270126      0.410225   0.296583    0.544914
 0.35298   0.186896   0.145625   …  0.159069  -0.0445074   0.397984
 0.561424  0.188273   0.173813      0.296516   0.11641     0.56948
 0.55839   0.397775   0.332633      0.360466   0.18777     0.577384
 0.467396  0.249965   0.208351      0.416795   0.35709     0.473687
 0.355193  0.304128   0.29814       0.364146   0.0184596   0.455219
 0.525594  0.420253   0.376952   …  0.420633   0.244606    0.402642
 0.348042  0.420301   0.301694      0.164073  -0.0645485   0.313588
 0.526184  0.339301   0.394794      0.319792   0.056696    0.521999
 ⋮                               ⋱                         
 0.525345  0.512237   0.45699    

In [38]:
eigvals(online3)

550-element Vector{Float64}:
   1.490115480528107e-8
   1.4901155656400884e-8
   1.4901155872391005e-8
   1.490115613323758e-8
   1.4901156204213384e-8
   1.4901156393444052e-8
   1.4901156638709675e-8
   1.4901156924729584e-8
   1.490115698471609e-8
   1.4901157155734599e-8
   1.4901157540851426e-8
   1.4901157604121736e-8
   1.4901157727383425e-8
   ⋮
   4.035989113617441
   4.656069098974213
   4.8514797102263705
   5.004747771465608
   5.653712169971773
   6.123019817563541
   7.782996526653893
   9.555124579366282
  12.245419294974827
  25.0511650450622
  32.87844107991152
 206.65278937981748